# Create a new new tag when a PR is merged into develop
name: Bump version
on:
  pull_request:
    types:
      - closed
    branches:
      - develop
#
#jobs:
#  build:
#    if: github.event.pull_request.merged == true
#    runs-on: ubuntu-22.04
#    permissions:
#      contents: write
#    steps:
#    - uses: actions/checkout@v4
#      with:
#        ref: ${{ github.event.pull_request.merge_commit_sha }}
#        fetch-depth: '0'
#
#    - name: Bump version and push tag
#      uses: anothrNick/github-tag-action@1.70.0
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        WITH_V: true
#        PRERELEASE: true

#on:
#  push:
#    branches: [ "develop" ]
#  pull_request:
#    types: 
#      - closed
#    branches: [ "develop" ]

jobs:
  build:
#    runs-on: ubuntu-latest
#    permissions:
#      contents: write
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Github Tag Bump
        uses: anothrNick/github-tag-action@1.70.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BRANCH: develop