# Creates a release with build artifacts attached after a tag is created.
name: Build plugin

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: SynapseAgentLambda
        path: |
          **/target/*.jar
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          **/target/*.jar
        draft: false